---
# tasks file for vsftpd
- name: Install Aptitude
  apt: 
    name: aptitude 
    state: latest 
    update_cache: yes 
    force_apt_get: yes

- name: Install vsftpd
  apt:
    name: vsftpd
    state: latest
    update_cache: yes